calimero-network/admin-dashboard

- src/utils/storage.ts
> fix: verify node function

- package.json
- pnpm-lock.yaml
> chore: bump sdk version

- package.json
- pnpm-lock.yaml
- src/api/dataSource/NodeDataSource.ts
- src/api/httpClient.ts
- src/hooks/useAdminClient.ts
- src/utils/storage.ts
Added auth headers for protected admin api endpoints.
> feat: add auth headers to api calls

- src/utils/storage.ts
> fix: connection status

- src/api/dataSource/NodeDataSource.ts
- src/api/nodeApi.ts
- src/components/context/ContextTable.tsx
- src/pages/Contexts.tsx
Updated fetch contexts lists api code along with the node code for admin api
> feat: refactor fetch contexts list

- src/api/dataSource/NodeDataSource.ts
- src/api/nodeApi.ts
- src/pages/ContextDetails.tsx
> feat: refactor fetch context details

- src/api/dataSource/NodeDataSource.ts
- src/api/nodeApi.ts
- src/components/applications/ApplicationsTable.tsx
- src/pages/Applications.tsx
Updating admin ui API code so its generic for all calls. This will be split into multiple PR's so its easy to test and review
> feat: refactor fetch apps api code

- src/api/dataSource/NodeDataSource.ts
- src/api/nodeApi.ts
- src/pages/Contexts.tsx
Update delete context logic and return type to match other api return types
> feat: update delete context return type

- src/api/dataSource/NodeDataSource.ts
- src/api/nodeApi.ts
- src/pages/StartContext.tsx
> feat: update start context return type

- src/api/dataSource/NodeDataSource.ts
- src/api/nodeApi.ts
- src/components/identity/IdentityTable.tsx
- src/pages/Identity.tsx
- src/utils/rootkey.ts
Update getDID return type and extract logic for mapping root keys to ETH or NEAR into `mapApiResponseToObjects` function
> feat: update did root keys logic

- package.json
- pnpm-lock.yaml
- src/pages/AddMetamaskRootKey.tsx
Bump sdk version to fix the root key auth issue
> feat: bump sdk version and fix return path

- src/api/dataSource/NodeDataSource.ts
- src/utils/rootkey.ts
Reply PR for [this](https://github.com/calimero-network/admin-dashboard/pull/30#discussion_r1660503380) comment
> fix: cleanup additional chain id param in near network

- package.json
- pnpm-lock.yaml
> chore: bump sdk to 0.0.26

- src/components/protectedRoutes/ProtectedRoute.tsx
- src/pages/Applications.tsx
Prevent infinite renders caused by dep change.
> fix: applications page deps

- pnpm-lock.yaml
- src/api/dataSource/NodeDataSource.ts
- src/api/nodeApi.ts
- src/components/protectedRoutes/ProtectedRoute.tsx
Introducing `isAuthorized` flag caused user being redirected to `/auth `page before login with wallet result has been processed.
> fix: admin dashboard login issue

- src/api/dataSource/NodeDataSource.ts
- src/components/context/contextDetails/ClientKeyRowItem.tsx
Update ClientKey object with proper name (walletType -> wallet).
Update display function props to camel case.
#Fixes: [issue](https://github.com/calimero-network/core/issues/525)
Test:
> Context client key list

- src/components/context/ContextTable.tsx
- src/pages/JoinContext.tsx
- src/pages/StartContext.tsx
To unblock dev prev context creation and joining disabled from the admin dashboard.
> fix: remove start context

- src/api/dataSource/NodeDataSource.ts
- src/api/nodeApi.ts
- src/components/applications/ApplicationRowItem.tsx
- src/components/applications/ApplicationsTable.tsx
- src/components/context/ContextTable.tsx
- src/pages/ApplicationDetails.tsx
- src/pages/Applications.tsx
- src/pages/StartContext.tsx
As the logic for application installation has changed in the Admin API, the function arguments for installation and response type has changed.
In this PR the api response type is updated and also the UI components data fetching was updated.
> fix: install application and list application metadata

- src/App.tsx
- src/api/dataSource/NodeDataSource.ts
- src/components/applications/ApplicationsTable.tsx
- src/components/applications/InstallApplicationCard.tsx
- src/constants/en.global.json
- src/pages/Applications.tsx
- src/pages/InstallApplication.tsx
Add install application page and update api call to match updated node api.
> Feat install app

- src/components/applications/ApplicationsTable.tsx
- src/components/applications/details/DetailsCard.tsx
- src/components/common/ListTable.tsx
- src/components/context/startContext/ApplicationsPopup.tsx
- src/constants/ApplicationsConstants.ts
- src/constants/ContextConstants.ts
- src/constants/en.global.json
- src/pages/ApplicationDetails.tsx
- src/pages/Applications.tsx
https://github.com/user-attachments/assets/c5050567-1951-4eb9-bfbe-2a24d1876ecc
> feat: add marketplace apps

- src/api/dataSource/NodeDataSource.ts
- src/api/nodeApi.ts
- src/components/applications/ApplicationRowItem.tsx
- src/components/applications/details/ApplicationDetailsTable.tsx
- src/components/applications/details/ReleaseRowItem.tsx
- src/constants/en.global.json
- src/pages/ApplicationDetails.tsx
- src/pages/Applications.tsx
- src/pages/InstallApplication.tsx
- src/utils/metadata.ts
Fix:  App installed from registry through UI does not have details. I cannot see url to install it on coordinator
https://github.com/user-attachments/assets/4e845f20-ad7e-4f2a-ba8e-4c68f79d27fb
> fix: missing contract app id in installed apps

- src/hooks/useMetamask.tsx
- src/hooks/useNear.tsx
- src/pages/ApplicationDetails.tsx
- src/pages/Applications.tsx
- src/pages/InstallApplication.tsx
- src/pages/Near.tsx
Updated all code for apiClient calls. The "pnpm build" command did not catch errors - reasons why not updated the first time.
> fix: add serverdown prop to api client

- pnpm-lock.yaml
> fix: updated pnpm-lock.yml file

- pnpm-lock.yaml
- src/hooks/useIcp.tsx
fixed II login not to interfere with MM and other wallets
> Feat ii login

- src/api/dataSource/NodeDataSource.ts
- src/api/nodeApi.ts
- src/components/context/startContext/StartContextCard.tsx
- src/components/login/applicationLogin/StartContextPopup.tsx
- src/components/login/applicationLogin/StartContextStep.tsx
- src/constants/en.global.json
- src/pages/StartContext.tsx
Added select field for protocols on context creation
> Feat update protocol flag

- src/api/dataSource/NodeDataSource.ts
Identity endpoint was split into two new endpoints so this change is needed so admin dashboard only displays owned context identities.
No updates
> feat: update endpoint api

- src/components/context/startContext/StartContextCard.tsx
- src/components/login/applicationLogin/StartContextPopup.tsx
Create context for Stellar protocol from Admin UI.
Already covered
> feat: add Stellar context create

- src/components/context/startContext/StartContextCard.tsx
- src/components/login/applicationLogin/StartContextPopup.tsx
Option to create EVM context from node-ui 
TBD
> feat: evm context option

- pnpm-lock.yaml
- src/api/dataSource/NodeDataSource.ts
- src/auth/storage.ts
- src/components/context/contextDetails/ContextTable.tsx
- src/components/context/contextDetails/UserRowItem.tsx
- src/components/context/startContext/StartContextCard.tsx
- src/components/login/applicationLogin/AppLoginPopup.tsx
- src/components/login/applicationLogin/CreateAccessTokenStep.tsx
- src/components/login/applicationLogin/SelectContextStep.tsx
- src/components/login/applicationLogin/SelectIdentityStep.tsx
- src/components/login/applicationLogin/StartContextPopup.tsx
- src/constants/en.global.json
- src/context/AppLoginContext.tsx
- src/pages/ContextDetails.tsx
- src/pages/StartContext.tsx
Transfer node-ui changes from core repository. Includes these PR's: [PR1](https://github.com/calimero-network/core/pull/1209) , [PR2](https://github.com/calimero-network/core/pull/1177)
N/A
> feat: transfer node-ui changes

- build/index.html
Bump Admin Dashboard build files
> feat: bump build

- package.json
- pnpm-lock.yaml
- src/components/identity/IdentityTable.tsx
- src/components/keys/RootKeyProvidersWrapper.tsx
- src/components/keys/providers/UsernamePasswordProvider.tsx
- src/pages/Blobs.tsx
Added functionality for adding new username & password root keys from admin dashboard.
Fixed blob management in admin dashboard
TEST for username and password implementation:
https://github.com/user-attachments/assets/88d2fcab-5bba-43d7-b56b-a220f6593fa1
> feat(Auth): added option to add new username password root key

- src/components/common/ListTable.tsx
- src/components/context/startContext/StartContextCard.tsx
- src/pages/StartContext.tsx
Corrected logic and frontend to include field for application initalization parameters.
> fix(Context): Creating context with application arguments

- package.json
- pnpm-lock.yaml
Includes update to login page where it has additional setup for node url.
> feat: bump calimero sdk version
